blank_issues_enabled: false

contact_links:
  - name: OBS Misa Translator README
    url: https://magicalshooter.github.io/OBSMisaTranslator/
    about: Please read the README before creating an issue.
