blank_issues_enabled: false

contact_links:
  - name: OBS Misa Translator
    url: https://magicalshooter.github.io/OBSMisaTranslator/
    about: OBS Misa Translator documentation.

  - name: VRC Misa Translator
    url: https://magicalshooter.github.io/vrc-misa-translator/
    about: VRC Misa Translator documentation.
